import Head from "next/head";
import { Sidebar } from "./sidebar";
import { ScrollArea } from "../ui/scroll-area";

interface ShellProps {
  children: React.ReactNode,
  sideBarSelection: 'tournaments' | 'teams' | 'players',
}

export function Shell({ children, sideBarSelection }: ShellProps) {
  return (
    <>
      <Head>
        <title>Bastec</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-background">
          <div className="flex flex-row min-w-screen min-h-screen  h-screen w-screen">
            <Sidebar className="w-[280px] fixed" sideBarSelection={sideBarSelection} />
            <div className="w-[280px]"></div>
            <div className="align-text-top flex-auto border-l">
              {children}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}